services:
  bookshelf-ui:
    container_name: bookshelf_ui
    image: node:20-alpine
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/appDistribuidos-main/bookshelf-ui
    command: sleep infinity
    ports:
      - "3000:3000"
    networks:
      - bookshelf

networks:
  bookshelf:

